name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
      - name: build phase
        run: echo "building app"
  
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test phase
        run: echo "testing app" 
  
  deploy: 
    runs-on: ubuntu-latest
    steps:
      - name: deploy phase
        run: echo "deloying app"
